language: node_js
node_js:
  - "12.18.0"

sudo: false

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - tsc --version
  - npm run vscode:prepublish

script:
  - npm run lint
  - npm test --silent
