# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Feature Request
description: Request a new feature for the project.
title: "[feature request] "
labels:
  - Feature Request
body:
  - id: description
    type: textarea
    attributes:
      label: Description
      description: A short description of the new feature being requested.
    validations:
      required: true
  - id: disclaimer
    type: checkboxes
    attributes:
      label: Disclaimer
      description: "By submitting this issue, you state the following:"
      options:
        - label: I have searched for existing issues and this is not a duplicate.
          required: true
        - label: I have read the project's contributing guidelines.
          required: true
        - label: I have read and understood the project's code of conduct.
          required: true
